-- 1.Top course within each category
-- Which courses are the top revenue genrators within each category?

-- ============================================================================
-- Query 1: Top Revenue-Generating Course Within Each Category
-- Business Question:
-- Which enrolled courses are the top revenue generators within each category?
-- ============================================================================

WITH CourseRevenue AS
(
    SELECT
        c.course_id,
        c.course_name,
        c.category,
        c.price,

        COUNT(e.enrollment_id) AS total_enrollments,

        c.price * COUNT(e.enrollment_id) AS total_revenue

    FROM courses c

    JOIN enrollments e
        ON c.course_id = e.course_id

    GROUP BY
        c.course_id,
        c.course_name,
        c.category,
        c.price
),

RankedCourses AS
(
    SELECT
        *,
        DENSE_RANK() OVER
        (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS revenue_rank

    FROM CourseRevenue
)

SELECT
    course_id,
    course_name,
    category,
    price,
    total_enrollments,
    total_revenue

FROM RankedCourses

WHERE revenue_rank = 1

ORDER BY
    category,
    course_name;

-- 2.Courses generating above average revenue
-- Which courses generate more revenue than the average course?

WITH CourseRevenue AS
(
    SELECT
        c.course_id,
        c.course_name,
        c.category,
        c.price,

        COUNT(e.enrollment_id) AS total_enrollments,

        c.price * COUNT(e.enrollment_id) AS total_revenue

    FROM courses c

    JOIN enrollments e
        ON c.course_id = e.course_id

    GROUP BY
        c.course_id,
        c.course_name,
        c.category,
        c.price
),

RevenueBenchmark AS
(
    SELECT
        AVG(total_revenue) AS average_course_revenue
    FROM CourseRevenue
)

SELECT
    cr.course_id,
    cr.course_name,
    cr.category,
    cr.price,
    cr.total_enrollments,
    cr.total_revenue,

    ROUND(rb.average_course_revenue, 2) AS average_course_revenue

FROM CourseRevenue cr

CROSS JOIN RevenueBenchmark rb

WHERE
    cr.total_revenue > rb.average_course_revenue

ORDER BY
    cr.total_revenue DESC;


-- 3.Students learning across multiple categories
-- Which students are learning across multiple course categories

SELECT 
	s.student_id,
	CONCAT(s.first_name,' ',s.last_name) student_name,
	COUNT(DISTINCT c.course_id) courses_enrolled,
	COUNT(DISTINCT c.category) categoies_eenrolled
FROM
	dbo.students s 
JOIN
	dbo.enrollments e 
ON
	s.student_id = e.student_id 
JOIN
	dbo.courses c 
ON
	e.course_id = c.course_id 
GROUP BY
	s.student_id,
	CONCAT(s.first_name,' ',s.last_name)
HAVING 
	COUNT(DISTINCT c.category) > 1
ORDER BY
	categoies_eenrolled DESC,
	courses_enrolled DESC;

-- 4.High Enrollment but low completion rate
-- Which courses attract many students but have below-average completion rate?

WITH CoursePerformance AS
(
    SELECT
        c.course_id,
        c.course_name,
        c.category,

        COUNT(e.enrollment_id) AS total_enrollments,

        SUM(
            CASE
                WHEN e.completion_status = 'Completed'
                THEN 1
                ELSE 0
            END
        ) AS completed_enrollments,

        ROUND(
            100.0 *
            SUM(
                CASE
                    WHEN e.completion_status = 'Completed'
                    THEN 1
                    ELSE 0
                END
            )
            / NULLIF(COUNT(e.enrollment_id), 0),
            2
        ) AS completion_rate

    FROM courses c
    LEFT JOIN enrollments e
        ON c.course_id = e.course_id

    GROUP BY
        c.course_id,
        c.course_name,
        c.category
),
Benchmarks AS
(
    SELECT
        AVG(total_enrollments) AS avg_enrollments,
        AVG(completion_rate) AS avg_completion_rate
    FROM CoursePerformance
    WHERE total_enrollments > 0
)
SELECT
    cp.course_id,
    cp.course_name,
    cp.category,
    cp.total_enrollments,
    cp.completion_rate,
    ROUND(b.avg_enrollments, 2) AS avg_enrollments,
    ROUND(b.avg_completion_rate, 2) AS avg_completion_rate
FROM CoursePerformance cp
CROSS JOIN Benchmarks b
WHERE
    cp.total_enrollments > b.avg_enrollments
    AND cp.completion_rate < b.avg_completion_rate
ORDER BY
    cp.total_enrollments DESC;
    
-- 5.Instructor Revenue Contribution
-- What percentage of total platform revenue is generated by each instructor?
    
WITH CourseRevenue AS
(
    SELECT
        c.course_id,
        c.instructor_id,

        COUNT(e.enrollment_id) AS total_enrollments,

        c.price * COUNT(e.enrollment_id) AS course_revenue

    FROM courses c

    JOIN enrollments e
        ON c.course_id = e.course_id

    GROUP BY
        c.course_id,
        c.instructor_id,
        c.price
),

InstructorRevenue AS
(
    SELECT
        i.instructor_id,
        i.instructor_name,

        SUM(cr.total_enrollments) AS total_enrollments,

        SUM(cr.course_revenue) AS total_revenue

    FROM instructors i

    JOIN CourseRevenue cr
        ON i.instructor_id = cr.instructor_id

    GROUP BY
        i.instructor_id,
        i.instructor_name
)

SELECT
    instructor_id,
    instructor_name,
    total_enrollments,
    total_revenue,

    ROUND(
        100.0 * total_revenue
        / NULLIF(SUM(total_revenue) OVER (), 0),
        2
    ) AS revenue_contribution_pct

FROM InstructorRevenue

ORDER BY
    total_revenue DESC;
